#ifndef HVACSERVICEQPHIDGET_GLOBAL_H
#define HVACSERVICEQPHIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HVACSERVICEQPHIDGET_LIBRARY)
#  define HVACSERVICEQPHIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HVACSERVICEQPHIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HVACSERVICEQPHIDGET_GLOBAL_H
